### PR TITLE
Add support for subjectAlternativeNames

### PR DESCRIPTION
**Pull request by ricardonooijen**
When checking if the certificate matches the hostname we connect to, we
should also check the subjectAlternativeName fields. Some servers
use MDC (Multi Domain Certificate) certificates which might have the
hostname listed in the SubjectAlternativeNames.

### CODE REVIEW

**Comment by Moosemorals** [comment]
Looks good at first review. I'm away from my development machine for a few more days, but I'll have a closer look (and probably accept) next week sometime.

**Comment by Moosemorals** [comment]
Awesome, thanks very much!
I'll get a new version pushed to Maven central just as soon as I find the recipe......

**Comment by ricardonooijen** [comment]
Thanks for accepting!

Could you give me a heads-up whenever you’ve pushed a new version to the maven repository (if you haven’t already)?

**Comment by Moosemorals** [comment]
Version 0.2 is up on [Maven Central](https://search.maven.org/#artifactdetails%7Ccom.fluffypeople%7Cmanagesievej%7C0.2.0%7Cjar).

**Comment by ricardonooijen** [comment]
Ty! ;)

**Pull request merged**
